### ISSUE TITLE
Access from GPU kernel

### ISSUE THREAD

**Issue by archenroot** [Overv/vramfs#11]
This project is really cool, I like the idea to use as much as possible fast resources.

If I understand it correctly If I will write implementation to access the file directly from OpenCL or CUDA, I will need to go trough host as it is using FUSE kernel integration, correct? So this doesn't make sense much.

Is there anyway or easy extension which will make the file accessible directly from GPU? Maybe it is even not good idea at all, but just came to my head.

Thanks for discussion.

Ladislav

**Comment by Overv** [comment]
Using vramfs for loading data into OpenCL/CUDA kernels doesn't really make any sense. You should just upload the file contents the regular way in that case.

**Comment by archenroot** [comment]
Yes, I also got to this point after small brainstorming :-)
