### ISSUE TITLE
error: could not allocate more than 0 bytes

### ISSUE THREAD

**Issue by terran2** [Overv/vramfs#15]
Hi, what does that mean?

`$ bin/vramfs vram1/ 2G
allocating vram...
error: could not allocate more than 0 bytes
cleaning up...
`

`$ bin/vramfs 
usage: vramfs <mountdir> <size> [-d <device>] [-f]

  mountdir    - directory to mount file system, must be empty
  size        - size of the disk in bytes
  -d <device> - specifies identifier of device to use
  -f          - flag that forces mounting, with a smaller size if needed

The size may be followed by one of the following multiplicative suffixes: K=1024, KB=1000, M=1024*1024, MB=1000*1000, G=1024*1024*1024, GB=1000*1000*1000. It's rounded up to the nearest multiple of the block size.

device list: 
  0: GeForce GT 730
`

**Comment by Overv** [comment]
Are you sure that OpenCL support is available for you?

**Comment by terran2** [comment]
I suppose 
```
GPU Engine Specs:
Up to 4.8xGeForce Performance Score1
Memory Specs:
DDR3/GDDR5Standard Memory Configuration
Feature Support:
4.5OpenGL
1.1OpenCL
PCI Express 3.0, PCI Express 2.0 Bus Support
YesCertified for Windows 7
YesCertified for Windows 8
Optimus, PhysX, CUDA, 3D Vision, FXAA, TXAA, OpenCL, Direct ComputeSupported Technologies
Yes3D Vision/3DTV Play Support
YesBlu-Ray 3D Support
12 API
```
https://www.geforce.com/hardware/notebook-gpus/geforce-gt-730m/specifications

**Comment by Overv** [comment]
Alright, but perhaps check if your OpenCL support is working correctly with the instructions listed [here](https://wiki.tiker.net/OpenCLHowTo).

**Comment by AndrusGerman** [comment]
Tengo las misma salida... Esta son mis especificaciones clinfo: https://textuploader.com/11hs4

**Comment by Overv** [comment]
@AndrusGerman Your graphics card doesn't support OpenCL 1.2.

**Comment by Overv** [comment]
@terran2 You don't have OpenCL 1.2 support either, which is the minimum requirement.
