### ISSUE TITLE
Vramfs get's stuck

### ISSUE THREAD

**Issue by quantmint** [Overv/vramfs#24]
When i run "vramfs /tmp/vram 3000MB -f", the output of the program is:
allocating vram...
mounted.
but the application never ends, it's stuck there forever i have to terminate the application with CTRL + C.
And the vram doesn't get allocated.

I am using a vega 56 on arch linux with opencl-amd installed.

**Comment by Overv** [comment]
It is normal for the application to continue running like that while the file system is mounted, so you should manually run it in the background if needed. If you are receiving the "mounted" message then the file system should be up and running on `/tmp/vram`. It's also normal to not see any VRAM usage until you actually start writing to the file system (driver optimizations).

Are you sure that it hasn't been mounted properly? Does it not show up as a separate file system in `df`?

**Comment by mberlinger3** [comment]
try:
`nohup vramfs /tmp/vram 3000MB -f &`
