### ISSUE TITLE
[Bug] vramfs deadlock caused by vramfs getting swapped to vram swap

### ISSUE THREAD

**Issue by Atrate** [Overv/vramfs#31]
Hello,

I have set-up swap on VRAM using `vramfs` and the guide from https://wiki.archlinux.org/title/Swap_on_video_RAM#FUSE_filesystem .

The problem appears when, under high memory pressure, `vramfs` gets swapped to VRAM, causing a complete deadlock.

Solution: use the `mlockall(MCL_CURRENT | MCL_FUTURE)` syscall to lock `vramfs`'s memory and not have it be swapped.

Workaround: https://github.com/Overv/vramfs/issues/3#issuecomment-1140448732

**Comment by Overv** [comment]
Could you make a PR to implement this solution? :) I'm not too familiar with `mlockall`, so I'm not sure where to put it.

**Comment by Atrate** [comment]
Me neither, I'm afraid. I just know that a syscall like that exists, but I haven't ever implemented it.
