### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by gcoimbra** [Overv/vramfs#34]
I'm observing about 6.59% of ram usage by vramfs process in a 16 GiB system. I'm allocating 8 GiB of vram. Is this normal?

**Comment by gcoimbra** [comment]
Actually, I have a further update. It seems that vramfs is allocating directly on system ram. I noticed that, after I use dd to fill an swapfile located on the directory mounted by vramfs, the memory showed as occupied in the GPU by radeontop decreases to zero (before it was full, as I use all VRAM with vramfs)

**Comment by twobombs** [comment]
# create vram tmpfs [ example assumes 24Gb card, change to your version  ]
mkdir /tmp/vram
./root/vramfs/bin/vramfs /tmp/vram/ 23G &
sleep 10
truncate -s 23G /tmp/vram/cache

# setup cache as a blockdevice
losetup /dev/loop33 /tmp/vram/cache

# create & mount swap
mkswap -f /dev/loop33
swapon /dev/loop33

**Comment by Green-Sky** [comment]
I think the nvidia driver now pins both, vram and system ram. I wonder with which version that started. (running Driver Version: 515.86.01)

**Comment by twobombs** [comment]
have not noticed this behaviour in Ubuntu 23.04 and NV 525.x
![Screenshot from 2023-03-26 14-55-59](https://user-images.githubusercontent.com/12692227/227777183-eafe3cd5-88fd-48dc-a5b5-b87eaf565b19.png)

**Comment by gcoimbra** [comment]
I think we can close this issue. I'm sorry I forgot to add here that I've discovered that because of problems with OpenCL drivers with AMD, the allocated memory by swapon was not in the GPU's VRAM, instead it was in my own RAM. That's why it reported that amount of memory utilization.
